[package]
name = "drc20-index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.56", features = ["backtrace"] }
axum = { version = "0.6.1", features = ["headers"] }
axum-server = "0.4.0"
base64 = "0.13.1"
bech32 = "0.9.1"
bip39 = "1.0.1"
bitcoin = { version = "0.29.1", features = ["rand"] }
boilerplate = { version = "0.2.3", features = ["axum"] }
chrono = "0.4.19"
clap = { version = "3.1.0", features = ["derive"] }
ctrlc = "3.2.1"
derive_more = "0.99.17"
dirs = "4.0.0"
env_logger = "0.10.0"
futures = "0.3.21"
hashbrown = "0.14.2"
hex = "0.4.3"
html-escaper = "0.2.0"
http = "0.2.6"
hyper = { version = "0.14.24", features = ["http1", "client"] }
indicatif = "0.17.1"
lazy_static = "1.4.0"
log = "0.4.14"
mime = "0.3.16"
mime_guess = "2.0.4"
miniscript = "9.0.0"
mp4 = "0.13.0"
bitcoincore-rpc = { git = "https://github.com/todcnst1453/rust-dogecoincore-rpc" }
redb = "0.13.0"
regex = "1.6.0"
rss = "2.0.1"
rust-embed = "6.4.0"
rustls = "0.20.6"
rustls-acme = { version = "0.5.0", features = ["axum"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81" }
serde_yaml = "0.9.17"
sys-info = "0.9.1"
tempfile = "3.2.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.9"
tokio-util = { version = "0.7.3", features = ["compat"] }
tower-http = { version = "0.3.3", features = [
    "compression-br",
    "compression-gzip",
    "cors",
    "set-header",
] }
sha2 = { version = "0.10", default-features = false }
ripemd = "0.1.3"

base58 = { version = "0.2" }
num-integer = "0.1"
[dev-dependencies]
executable-path = "1.0.0"
pretty_assertions = "1.2.1"
reqwest = { version = "0.11.10", features = ["blocking"] }
unindent = "0.2.1"
sha256 = "1.4.0"

[[bin]]
name = "dex"
path = "src/bin/main.rs"

[lib]
name = "dex"
path = "src/lib.rs"

[build-dependencies]
pulldown-cmark = "0.9.2"

[patch.crates-io]
bitcoin = { git = "https://github.com/apezord/rust-dogecoin" }
bitcoincore-rpc = { git = "https://github.com/todcnst1453/rust-dogecoincore-rpc" }
